import { category } from './build'

export const electronics = [
  category('electricity', 'Electricity', '↯', 'Charge, voltage and current from first principles', [
    ['Current', 'Charge in motion', ['What flows in a wire', ['Conventional vs electron flow', 'anim', 4], 'Amps and the coulomb']],
    ['Voltage', 'The push behind the charge', ['Potential difference', 'Ground and reference', 'Measuring with a multimeter']],
    ['Resistance', 'Why wires and parts resist flow', ['Resistivity and wire gauge', 'Temperature effects', ['Reading resistor bands', 'sim', 4]]],
    ["Ohm's law", 'V, I and R in one loop', ['V = I × R', 'Solving a loop', ['Ohm plot', 'anim', 3]]],
    ['Power & energy', 'Watts, heat and battery life', ['P = V × I', 'Heat in a resistor', 'Wh and mAh']],
    ['Series & parallel', 'How resistors and cells combine', ['Series resistors', 'Parallel resistors', 'Cells in series and parallel', 'Mixed networks']],
    ['Voltage divider', 'Two resistors, one reading', ['The divider formula', 'Loading a divider', 'Divider as a sensor input']],
    ["Kirchhoff's laws", 'Currents in, currents out', ['KCL at a node', 'KVL around a loop', ['Nodal analysis', 'sim', 5]]],
    ['Thevenin & Norton', 'Collapse a circuit to one source', ['Thevenin equivalent', 'Maximum power transfer']],
    ['AC vs DC', 'Steady flow versus sloshing', ['Sine waves and RMS', 'Frequency and period', ['Mains vs battery', 'anim', 3]]],
    ['Electric fields', 'Force without touching', ['Coulomb force', 'Field lines', 'Capacitance from plates']],
    ['Magnetism', 'Fields from moving charge', ['Wire and compass', 'Solenoid', 'Right-hand rule', 'Induction']],
  ]),
  category('components', 'Components', '◧', 'The passive and discrete parts on every board', [
    ['Resistor', 'Limit, divide, pull up', ['Value and tolerance', 'Power rating', 'Pull-up and pull-down']],
    ['Capacitor', 'A tiny bucket of charge', ['Charging and discharging', 'RC time constant', 'Decoupling', 'Electrolytic vs ceramic']],
    ['Inductor', 'Current that resists change', ['Energy in a coil', 'RL time constant', 'Flyback spike']],
    ['Diode', 'A one-way valve', ['Forward drop', 'Reverse blocking', 'Flyback diode', 'Zener clamp']],
    ['LED', 'A diode that glows', ['Forward voltage and colour', 'Current-limiting resistor', 'RGB LED', 'LED matrix']],
    ['Transistor (BJT)', 'A small current steering a big one', ['NPN as a switch', 'Gain and saturation', 'Base resistor']],
    ['MOSFET', 'A voltage-controlled switch', ['Gate threshold', 'Low-side switching', 'Logic-level MOSFETs', 'Gate drive']],
    ['Relay', 'A switch moved by a magnet', ['Coil and contacts', 'Driving a relay', 'Solid-state relay']],
    ['Switches & buttons', 'Making and breaking a circuit', ['Contact bounce', 'Debouncing', 'Toggle vs momentary']],
    ['Potentiometer', 'A knob that divides voltage', ['Wiper as divider', 'Linear vs log taper']],
    ['Fuses & protection', 'Fail safe, not fail fire', ['Fuse ratings', 'Reverse-polarity protection', 'TVS diode']],
    ['Crystal oscillator', 'The heartbeat of a clock', ['Resonance', 'Load capacitors', 'Clock accuracy']],
    ['Op-amp', 'Amplify the difference', ['Ideal rules', 'Inverting amplifier', 'Voltage follower', 'Comparator']],
    ['Voltage regulators', 'A steady rail from a messy source', ['Linear LDO', 'Dropout and heat', 'Buck converter', 'Boost converter']],
  ]),
  category('semiconductors', 'Semiconductors', '▦', 'From silicon crystal to logic', [
    ['Silicon & doping', 'Making a conductor on demand', ['Band gap', 'N-type and P-type', ['Holes and electrons', 'anim', 4]]],
    ['PN junction', 'Where a diode really lives', ['Depletion region', 'Forward and reverse bias', 'Breakdown']],
    ['MOSFET physics', 'The switch inside every chip', ['Channel formation', 'CMOS inverter', 'Switching energy']],
    ['Logic gates', 'AND, OR, NOT from transistors', ['NAND from transistors', 'Truth tables', 'Adders']],
    ['Memory cell', 'How a bit is stored', ['SRAM latch', 'DRAM capacitor', 'Flash floating gate']],
    ['Chip making', 'From sand to wafer to package', [['Lithography machine', 'anim', 5], ['Wafer to chip', 'anim', 5], ['What 3 nm means', 'anim', 4]]],
    ['Photodiodes & solar cells', 'Light in, current out', ['Photovoltaic effect', 'Light sensing']],
  ]),
  category('digital', 'Digital logic', '⌗', 'Bits, gates and state machines', [
    ['Binary & hex', 'Counting in two and sixteen', ['Binary counting', 'Hex shorthand', 'Two’s complement']],
    ['Combinational logic', 'Outputs from inputs alone', ['Truth tables', 'Multiplexer', 'Decoder', 'Half and full adder']],
    ['Flip-flops & latches', 'Logic with memory', ['SR latch', 'D flip-flop', 'Registers']],
    ['Counters & shift registers', 'Sequencing bits', ['Ripple counter', 'Shift register', '74HC595 output expander']],
    ['State machines', 'Behaviour as states and transitions', ['Moore vs Mealy', 'Traffic light FSM', 'Robot behaviour FSM']],
    ['Timing', 'Clocks, setup and hold', ['Propagation delay', 'Metastability', 'Clock dividers']],
    ['Level shifting', '3.3 V meets 5 V', ['Logic thresholds', 'Divider shifter', 'Bidirectional shifter']],
    ['FPGA basics', 'Hardware you can rewire', ['LUTs', 'Blinky in hardware']],
  ]),
  category('microcontrollers', 'Microcontrollers', '▣', 'ESP32, Arduino and the peripherals inside', [
    ['GPIO', 'Pins as inputs and outputs', ['Output and input modes', 'Pull-ups', 'Drive strength', 'Interrupts']],
    ['PWM', 'Dimming and speed by fast switching', ['Duty cycle', 'Frequency choice', 'Servo pulses', 'Average voltage']],
    ['ADC', 'Turning voltage into numbers', ['Resolution and range', 'Sampling', 'Noise and averaging', 'ESP32 ADC quirks']],
    ['DAC', 'Numbers back into voltage', ['R-2R ladder', 'Audio out']],
    ['Timers & interrupts', 'Doing things on schedule', ['Hardware timers', 'ISR rules', 'Millis without delay']],
    ['UART serial', 'Bits on a wire, one at a time', ['Framing and baud', 'Level and noise', 'GPS and modules']],
    ['I²C', 'Two wires, many chips', ['Addresses', 'Pull-up resistors', 'Reading an IMU', 'Bus scan']],
    ['SPI', 'Fast four-wire bus', ['Clock modes', 'Chip select', 'SD cards and displays']],
    ['CAN bus', 'Robust multi-node comms', ['Differential signalling', 'Arbitration']],
    ['Wi-Fi & Bluetooth', 'Radio on a $5 board', ['Station and AP', 'HTTP and WebSocket', 'BLE GATT', 'ESP-NOW']],
    ['Power modes', 'Sleep to sip the battery', ['Deep sleep', 'Wake sources', 'Battery budget']],
    ['Memory & storage', 'Flash, RAM and files', ['Flash layout', 'Stack and heap', 'LittleFS']],
    ['RTOS basics', 'Many tasks, one core', ['Tasks and priorities', 'Queues', 'Mutexes']],
    ['Bootloader & flashing', 'How code gets onto the chip', ['Boot modes', 'OTA updates']],
  ]),
  category('sensors', 'Sensors', '◉', 'How a robot perceives the world', [
    ['Ultrasonic', 'Distance from an echo', ['Time of flight', 'Beam angle', 'Soft-target errors']],
    ['Infrared', 'Seeing with invisible light', ['Obstacle sensor', 'Line follower', 'Sunlight interference']],
    ['Time-of-flight laser', 'Distance from light', ['VL53L0X', 'Multi-zone ranging']],
    ['LiDAR', 'A spinning laser map', ['2D scan', 'Point clouds', 'Resolution and range']],
    ['Encoder', 'Counting wheel turns', ['Quadrature', 'Counts per revolution', 'Speed from ticks']],
    ['IMU', 'Acceleration and rotation', ['Accelerometer', 'Gyroscope', 'Complementary filter', 'Drift']],
    ['Magnetometer', 'A digital compass', ['Heading', 'Hard-iron calibration']],
    ['GPS', 'Position from satellites', ['Trilateration', 'Fix and accuracy', 'RTK']],
    ['Camera', 'Pixels as a sensor', ['Rolling vs global shutter', 'Exposure', 'Lens distortion']],
    ['Temperature & humidity', 'DHT11, DS18B20, thermistor', ['Thermistor curve', 'One-wire protocol']],
    ['Current & voltage sensing', 'Know what the battery is doing', ['Shunt resistor', 'INA219', 'State of charge']],
    ['Force & touch', 'Load cells, bumpers, capacitive', ['Strain gauge', 'Capacitive touch']],
    ['Microphone & sound', 'Listening for direction', ['MEMS mic', 'Sound source direction']],
    ['Sensor fusion', 'Many weak sensors, one good answer', ['Why fuse', 'Complementary filter', 'Kalman intuition']],
  ]),
  category('power', 'Power systems', '▮', 'Batteries, regulation and wiring that doesn’t smoke', [
    ['Battery chemistry', 'Li-ion, LiPo, NiMH, lead-acid', ['Cell voltage curve', 'Capacity and C-rate', 'Internal resistance']],
    ['18650 packs', 'Series and parallel cells', ['1S to 4S', 'BMS protection', 'Balancing']],
    ['Charging', 'CC/CV and safety', ['TP4056', 'Charge curve', 'Thermal limits']],
    ['Buck & boost', 'Switching converters', ['Inductor ripple', 'Efficiency', 'Choosing a module']],
    ['Power budget', 'Sizing the battery to the robot', ['Add up the loads', 'Runtime estimate', 'Peak vs average']],
    ['Wiring & gauge', 'Thick enough, short enough', ['Voltage drop', 'Connector ratings', 'Star ground']],
    ['Noise & decoupling', 'Keeping motors out of the logic', ['Motor noise', 'Bulk capacitors', 'Separate rails']],
    ['Brownouts', 'When the MCU resets mid-move', ['Current spikes', 'Diagnosing resets']],
  ]),
  category('signals', 'Signals & EMC', '∿', 'Waveforms, filters and radio', [
    ['Filters', 'Keep the band you want', ['RC low-pass', 'High-pass', 'Bode plot']],
    ['Fourier intuition', 'Every signal is a sum of sines', ['Spectrum', 'Aliasing', 'Nyquist']],
    ['Oscilloscope', 'Seeing voltage over time', ['Triggering', 'Probing', 'Decoding a bus']],
    ['Logic analyzer', 'Watching digital buses', ['Capture UART', 'Capture I²C']],
    ['Transmission lines', 'When wires act like antennas', ['Reflections', 'Termination']],
    ['Radio basics', 'Carrier, modulation, range', ['2.4 GHz', 'Antenna types', 'LoRa']],
    ['Grounding & shielding', 'Taming interference', ['Ground loops', 'Ferrite beads']],
    ['PCB design', 'From schematic to board', ['Schematic capture', 'Layout rules', 'Traces and vias', 'Manufacturing']],
  ]),
]
