import { category } from './build'

export const physics = [
  category('mechanics', 'Mechanics', '⬡', 'Forces, torque and energy for moving things', [
    ['Newton’s laws', 'Force, mass, acceleration', ['F = m a', 'Free-body diagrams', 'Friction']],
    ['Kinematics', 'Position, velocity, acceleration', ['Constant acceleration', 'Velocity vs time plots', 'Projectile motion']],
    ['Torque & levers', 'Force at a distance', ['Moment arm', 'Lever types', 'Static balance']],
    ['Rotation', 'Angular speed and inertia', ['Moment of inertia', 'Angular momentum', 'Flywheel']],
    ['Energy & work', 'Where the joules go', ['Kinetic and potential', 'Work and power', 'Efficiency']],
    ['Friction & traction', 'Grip limits', ['Static vs kinetic', 'Rolling resistance', 'Wheel slip']],
    ['Oscillations', 'Springs and pendulums', ['Spring-mass', 'Damping', 'Resonance']],
    ['Collisions', 'Momentum transfer', ['Elastic and inelastic', 'Bump sensors']],
    ['Centre of mass', 'Why robots tip', ['Tipping angle', 'Low and wide']],
    ['Vibration', 'Shake, rattle and fix', ['Motor vibration', 'Damping mounts']],
  ]),
  category('materials', 'Materials & mechanical design', '⬢', 'Structures that hold up', [
    ['Stress & strain', 'How parts bend and break', ['Hooke’s law', 'Yield strength', 'Safety factor']],
    ['Laser & CNC', 'Cutting plates and frames', ['Kerf', 'Acrylic vs plywood']],
    ['Fasteners', 'Screws, nuts and inserts', ['Metric sizes', 'Heat-set inserts', 'Thread locker']],
    ['Bearings', 'Spin without scraping', ['Ball bearings', 'Bushings']],
    ['Belts, chains, couplers', 'Moving torque around', ['Timing belt', 'Shaft couplers']],
    ['CAD basics', 'Drawing parts', ['Sketch and extrude', 'Assemblies', 'Exporting STL']],
    ['Chassis design', 'The skeleton of a robot', ['Layout and balance', 'Cable routing']],
    ['Thermal design', 'Heat has to go somewhere', ['Heatsinks', 'Motor heating']],
  ]),
  category('printing', '3D printing', '⬒', 'From CAD model to printed robot part', [
    ['How FDM works', 'Melt, extrude, stack layers', [['Anatomy of a printer', 'sim', 4], ['Hotend and extruder', 'anim', 4], 'Layer by layer', 'Cartesian, CoreXY, delta']],
    ['Other processes', 'Resin, powder and more', ['SLA and MSLA resin', 'SLS nylon powder', 'Choosing a process']],
    ['Printer motion', 'Steppers, belts and G-code moves', ['Axes and endstops', 'Belts vs lead screws', 'Steps per mm', 'Input shaping']],
    ['Filaments', 'PLA, PETG, ABS, TPU, nylon', ['Material properties', 'Glass transition temp', 'Flexible TPU', 'Carbon-fibre blends', 'Drying wet filament']],
    ['Slicing', 'Turning a mesh into toolpaths', ['STL and 3MF', 'Layer height', 'Walls and perimeters', 'Infill patterns', 'Supports', 'Seams']],
    ['G-code', 'The language the printer speaks', ['G0, G1 moves', 'Temperatures and fans', 'Start and end scripts']],
    ['Temperature & cooling', 'Heat in the right places', ['Hotend PID tuning', 'Heated bed', 'Part cooling fan', 'Thermal runaway protection']],
    ['Bed adhesion', 'The first layer decides everything', ['Bed levelling', 'Z offset', 'Build surfaces', 'Brim and raft']],
    ['Calibration', 'Dialling in a printer', ['E-steps', 'Flow rate', 'Pressure advance', 'Retraction', 'Temperature tower']],
    ['Print problems', 'Diagnose the failure', ['Stringing', 'Warping', 'Layer shift', 'Under-extrusion', 'Elephant foot', 'Clogged nozzle']],
    ['Design for printing', 'Parts that print well', ['Overhangs and bridges', 'Orientation and strength', 'Tolerances and fits', 'Holes and teardrops', 'Chamfers vs fillets']],
    ['Functional parts', 'Robot parts that last', ['Heat-set inserts', 'Captive nuts', 'Snap fits', 'Living hinges', 'Printed gears']],
    ['Strength', 'Why parts break along layers', ['Layer adhesion', 'Wall count vs infill', 'Annealing']],
    ['Multi-material', 'Colours and dissolvable supports', ['Tool changers and AMS', 'Soluble supports']],
    ['Post-processing', 'Finishing a print', ['Sanding and filling', 'Vapour smoothing', 'Painting']],
    ['Printer electronics', 'The mainboard and firmware', ['Mainboard and drivers', 'Marlin and Klipper', 'Thermistors and heaters']],
    ['Print a robot', 'A chassis from CAD to car', [['Model the chassis', 'build', 10], ['Slice and print', 'build', 8], ['Assemble with inserts', 'build', 8]]],
  ]),
  category('waves', 'Waves, light & heat', '〰', 'The physics behind sensors', [
    ['Sound & ultrasound', 'Pressure waves', ['Speed of sound', 'Echo ranging', 'Doppler']],
    ['Light & optics', 'Rays, lenses, colour', ['Reflection', 'Refraction', 'Lenses and focus']],
    ['Infrared & thermal', 'Heat you can sense', ['Black-body radiation', 'Thermal camera']],
    ['Electromagnetic spectrum', 'From radio to X-rays', ['Wavelength and frequency', 'Where sensors live']],
    ['Heat transfer', 'Conduction, convection, radiation', ['Thermal resistance', 'Cooling a regulator']],
    ['Pressure & fluids', 'Air and water', ['Bernoulli', 'Barometer altitude']],
    ['Gravity & inertia', 'What an IMU actually feels', ['Free fall', 'Accelerometer reading']],
  ]),
  category('math', 'Maths for robots', '∑', 'Just enough maths, visually', [
    ['Vectors', 'Direction and size', ['Dot product', 'Cross product', 'Projection']],
    ['Matrices', 'Transform everything', ['Rotation matrix', 'Matrix multiply', 'Inverse']],
    ['Trigonometry', 'Angles and triangles', ['Unit circle', 'atan2', 'Law of cosines']],
    ['Quaternions', 'Rotation without gimbal lock', ['Gimbal lock', 'Quaternion rotate', 'SLERP']],
    ['Calculus', 'Rates and accumulation', ['Derivative as slope', 'Integral as area', 'Numerical integration']],
    ['Probability', 'Dealing with noise', ['Gaussian noise', 'Bayes rule', 'Variance']],
    ['Linear algebra', 'Systems and solving', ['Least squares', 'Eigenvectors']],
    ['Differential equations', 'Motion as a rule', ['Euler integration', 'Step size']],
    ['Signals', 'Sampling and discretization', ['Sample rate', 'Z-transform intuition']],
  ]),
]
