import { category } from './build'

export const robotics = [
  category('actuators', 'Motors & actuators', '⚙', 'Turning electrons into motion', [
    ['DC motor', 'Magnets, coils and torque', ['Back-EMF', 'Torque and speed curve', 'Stall current', 'Gearboxes']],
    ['H-bridge', 'Forward, reverse, brake', ['Four switches', 'L298N vs modern drivers', 'Decay modes', 'Shoot-through']],
    ['Servo', 'Hold an angle with feedback', ['Pulse to angle', 'Inside a hobby servo', 'Jitter and power']],
    ['Stepper', 'Precise turns, one step at a time', ['Full, half and micro-steps', 'A4988 and TMC drivers', 'Missed steps']],
    ['Brushless (BLDC)', 'Electronic commutation', ['Three-phase drive', 'Hall sensors', 'ESC basics']],
    ['Field-oriented control', 'Smooth torque from BLDC', ['Clarke and Park', 'Current loops']],
    ['Linear actuators', 'Push and pull in a line', ['Lead screw', 'Limit switches']],
    ['Solenoids & pumps', 'Small on/off actuators', ['Solenoid drive', 'Peristaltic pump']],
    ['Gear trains', 'Trade speed for torque', ['Gear ratio', 'Backlash', 'Planetary gears', 'Worm drive']],
    ['Pneumatics & soft robots', 'Moving with air', ['Pneumatic cylinder', 'Soft gripper']],
    ['Motor selection', 'Choosing for a load', ['Torque budget', 'Duty cycle', 'Thermal limits']],
  ]),
  category('mobility', 'Wheels & drive', '◎', 'How a robot gets around', [
    ['Differential drive', 'Steering with two wheels', ['Turn radius', 'Odometry', 'Slip']],
    ['Mecanum wheels', 'Driving sideways', ['Roller geometry', 'Strafe maths', 'Why they slip']],
    ['Omni & swerve', 'Holonomic alternatives', ['Omni wheels', 'Swerve module']],
    ['Ackermann steering', 'How a car turns', ['Steering geometry', 'Bicycle model']],
    ['Tracks & terrain', 'Tank treads and rough ground', ['Skid steer', 'Traction']],
    ['Legged walking', 'Biped, quadruped, hexapod', ['Gait cycle', 'Zero-moment point', 'Leg IK']],
    ['Balancing robots', 'The inverted pendulum', ['Why it falls', 'Tilt PID', 'Self-balancing car']],
    ['Drones & flight', 'Thrust, lift and stability', ['Quadcopter mixing', 'Attitude control']],
    ['Underwater & swimming', 'Thrusters and buoyancy', ['Buoyancy', 'Thruster layout']],
  ]),
  category('control', 'Control', '↻', 'Feedback loops that keep robots on target', [
    ['Open vs closed loop', 'Why feedback matters', ['Dead reckoning drift', 'Closing the loop']],
    ['Bang-bang & hysteresis', 'The simplest controller', ['Thermostat', 'Chatter']],
    ['PID', 'Proportional, integral, derivative', ['Proportional only', 'Integral windup', 'Derivative kick', 'Tuning by hand', 'Ziegler–Nichols']],
    ['Speed control', 'Hold a wheel speed', ['Encoder feedback', 'Feed-forward', 'Velocity PID']],
    ['Position control', 'Reach and hold a target', ['Trapezoid profile', 'S-curve']],
    ['Line following', 'A feedback loop on wheels', ['Error from sensors', 'PD steering', 'Intersections']],
    ['Stability', 'When loops oscillate', ['Poles and damping', 'Step response', 'Gain and phase margin']],
    ['State-space & LQR', 'Optimal feedback', ['State vector', 'LQR intuition']],
    ['Model predictive control', 'Plan, apply, repeat', ['Receding horizon', 'Constraints']],
    ['Filters in the loop', 'Cleaning the measurement', ['Moving average', 'Low-pass', 'Kalman filter']],
  ]),
  category('kinematics', 'Kinematics & arms', '⌖', 'Geometry of joints and end-effectors', [
    ['Coordinate frames', 'Where is everything?', ['2D rotation', 'Homogeneous transforms', 'Frame tree']],
    ['Forward kinematics', 'Joint angles to hand position', ['Two-link arm', 'Denavit–Hartenberg']],
    ['Inverse kinematics', 'Hand position to joint angles', ['Analytic IK', 'Multiple solutions', 'Jacobian method']],
    ['Jacobian', 'Joint speed to hand speed', ['Singularities', 'Manipulability']],
    ['Workspace', 'What the arm can reach', ['Reach envelope', 'Dexterity']],
    ['Trajectories', 'Smooth motion in time', ['Linear interpolation', 'Splines', 'Time scaling']],
    ['Grippers', 'Holding things', ['Parallel jaw', 'Suction', 'Compliance']],
    ['Robot arm build', 'A 4-DOF servo arm', [['Assemble the arm', 'build', 10], ['Drive it with IK', 'build', 8]]],
    ['Dynamics', 'Forces on a moving arm', ['Gravity torque', 'Inertia', 'Payload limits']],
  ]),
  category('perception', 'Vision & perception', '◍', 'Making sense of sensor data', [
    ['Image basics', 'Pixels and colour', ['RGB and HSV', 'Thresholding', 'Histogram']],
    ['Edges & features', 'What stands out', ['Convolution', 'Canny edges', 'Corners']],
    ['Colour tracking', 'Follow a ball', ['HSV mask', 'Centroid steering']],
    ['Camera model', 'Pixels to rays', ['Pinhole model', 'Calibration', 'Stereo depth']],
    ['Fiducial markers', 'AprilTags and ArUco', ['Detecting a tag', 'Pose from a tag']],
    ['Object detection', 'Boxes from a neural net', ['YOLO idea', 'Running on an ESP32-CAM', 'Edge accelerators']],
    ['Depth sensing', 'Stereo, ToF and structured light', ['Depth map', 'Point cloud']],
    ['Optical flow', 'Motion from video', ['Lucas–Kanade', 'Visual odometry']],
    ['Occupancy grids', 'A map of free and blocked', ['Ray casting', 'Log-odds update']],
  ]),
  category('navigation', 'Navigation & planning', '➤', 'Going from A to B without hitting C', [
    ['Odometry', 'Where am I from wheel ticks?', ['Dead reckoning', 'Error growth', 'Calibrating wheel size']],
    ['Obstacle avoidance', 'Sensor to motor, end to end', ['Reactive rules', 'Braitenberg vehicles', 'Wall following']],
    ['Maze solving', 'Left-hand rule to flood fill', ['Wall follower', 'Flood fill', 'Micromouse']],
    ['Graph search', 'BFS, Dijkstra, A*', ['Grid maps', 'A* heuristic', 'D* Lite']],
    ['Sampling planners', 'RRT and PRM', ['RRT growth', 'Smoothing paths']],
    ['Path tracking', 'Follow the route', ['Pure pursuit', 'Stanley controller']],
    ['Localization', 'Which spot on the map?', ['Particle filter', 'Scan matching']],
    ['SLAM', 'Map and locate at once', ['The chicken-and-egg problem', 'Loop closure', 'Pose graphs']],
    ['Swarm & multi-robot', 'Many robots, one job', ['Flocking', 'Task allocation']],
  ]),
  category('software', 'Robot software', '⌘', 'The code layer: ROS, firmware and tools', [
    ['Firmware structure', 'Loops, tasks and drivers', ['Super-loop vs RTOS', 'Hardware abstraction', 'Fixed-rate control loop']],
    ['ROS 2 concepts', 'Nodes, topics and services', ['Publish and subscribe', 'Services and actions', 'Launch files']],
    ['TF & URDF', 'Describing the robot', ['Frame tree', 'Writing a URDF']],
    ['Nav2', 'Navigation stack tour', ['Costmaps', 'Behaviour trees']],
    ['micro-ROS', 'ROS on a microcontroller', ['Agent and client', 'Serial transport']],
    ['Simulation', 'Gazebo and friends', ['Physics engine', 'Sim-to-real gap']],
    ['Behaviour trees', 'Structured autonomy', ['Sequence and fallback', 'Blackboard']],
    ['Telemetry & logging', 'See what the robot saw', ['Plotting live data', 'Replay logs']],
    ['Remote control', 'Drive it from your phone', ['Joystick over BLE', 'WebSocket control', 'Latency']],
    ['Safety & failsafes', 'Stop when something is wrong', ['Watchdog', 'E-stop', 'Fault states']],
  ]),
  category('ai', 'AI for robots', '✦', 'Learning, vision and language on the edge', [
    ['Neural nets 101', 'Neurons, layers, training', ['Perceptron', 'Gradient descent', 'Overfitting']],
    ['TinyML', 'Models on a microcontroller', ['Quantization', 'Gesture recognition']],
    ['Reinforcement learning', 'Learning by trial and reward', ['Reward and policy', 'Q-learning gridworld', 'Sim to real']],
    ['Imitation learning', 'Learn from demonstrations', ['Behaviour cloning', 'Data collection']],
    ['Vision-language models', 'Instructions in plain words', ['Grounding objects', 'Task planning']],
    ['Speech & wake words', 'Talk to your robot', ['Keyword spotting', 'Voice commands']],
    ['Anomaly detection', 'Notice when something is off', ['Vibration baselines', 'Thresholds vs models']],
  ]),
]
